### ISSUE TITLE
Hamburger Menu Fails to Open on Home Page

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#100]
I looked at this briefly this morning, but I didn't notice what might be causing the issue. If someone else could take a look, I'd appreciate it.

**Comment by kenirwin** [comment]
A little testing suggests the problem was introduced in this commit:
1fd7c3a move session-table script to main scripts folder
I'm guessing it happened in the scripts.js file.

Unfortunately, my editor extension (VSCode+Prettier) decided to reformat the whole file on the commit, so it's hard to pinpoint what exact changes happened there. I'll see if I can find anything further.

**Comment by dzoladz** [comment]
@kenirwin Is it the Prettier plugin that does this?
```html
<element
     class=""
     attributes=""
     etc=""
>
```
