### ISSUE TITLE
Main Poster Navigation is Cumbersome

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#64]
I'd like us to consider using a simple list as the main organizational structure of individual posters access points.

As an example of a categorized list: https://acrl.ala.org/DLS/2020-virtual-poster-session/
Our current version: https://2020.alaoweb.org/posters/

**Comment by dzoladz** [comment]
Card Style and List demos for team

**Comment by dzoladz** [comment]
Team would like to continue exploring a card-based structure, to simulate the activity of scanning a room of posters and interacting with those with interesting appeal.
 
Since we don’t have a solid understanding of the types of content that will be submitted as a poster this year, we might not be able to engineer a design that’s image-orientated and derived from the poster’s content.
 
Would it be possible to create a design that reads the title from the poster front matter and creates something similar to a title slide?

![Screen Shot 2020-08-24 at 3 57 38 PM](https://user-images.githubusercontent.com/10561752/91098539-a0921100-e62f-11ea-84ae-8809a4a85521.png)

__^ btw... not an endorsement of this design by any means__

**Comment by dwgreen1** [comment]
I have added a poster-list branch that has a new card-like layout. I've played with this in several ways, and I run into hurdles the more complicated (i.e. pretty) I try to make it. Without randomizing the backgrounds of each card, a background for each is going to look repetitive and messy, so I went with something generic. Likewise, trying to go for a multi-column layout introduced issues in which the cards were not the same height, and I could not figure out (in time) how to make it happen.

To test this out, please enable <code>showPosters: true</code> in <code>_config.yml</code> and let me know your thoughts the background and layout. If you have ideas about how to prettify this, I'm all ears. I just couldn't find a way that wasn't too complicated.

**Question - main.css**
Does anyone know why there is a max-width defined in <code>main.css</code> on the poster layout? I was going to try to maintain the width of the cards through Bootstrap classes, but width is defined in main.css instead, and that particular file is minified. I wasn't sure if I should be touching this file or if I'm missing something.

**Question - random order**
I also looked into randomizing the order of the posters. This is definitely possible in one of two ways: pre-build via Jekyll and post-build via JavaScript. Both have their drawbacks though... 

In a _pre-build_, the order will be randomized, but this only randomizes it for the build. Unless we are rebuilding frequently, the order will remain the same while visitors look at the site. It wouldn't be a terrible idea (I guess?) to randomize the order in a build just so that we can sleep easy at night knowing we didn't put it in any particular order. 

In a _post-build_ JavaScript script, the order can be randomized easily; however, this also means that the order of the posters is going to change every time a user navigates back to the list. I can see this easily frustrating someone who is trying to browse down the list but they lose their spot each time because the list has changed. You can uncomment the code at the bottom of <code>posters.html</code> to see how this works, but I definitely do not recommend this approach.

**Comment by dzoladz** [comment]
Thanks @dwgreen1. I plan to take a look at this over the next day or so. Feel free to continue pushing commits are you see fit.

**Comment by dwgreen1** [comment]
I was able to figure out the CSS issue, so we can ignore that now. I'm relying instead on the Bootstrap classes to handle the layout and width of cards based on the viewport instead. Meanwhile, I attempted a couple of times to display the posters in a two-column layout instead of a single-column but I ran into issues, still. At first, I thought I would use the <code>card-deck</code> class to keep the height of both cards equal for each set of two; however, that class seems to be missing, so it had no effect.

**Comment by dzoladz** [comment]
I pulled down this branch and, as-is, will work just fine. In my experience, I found that the Bootstrap examples are often these perfect use cases devised to display the functionality of the framework in an ideal manner.

I'll take a quick look at the organizing the cards into a two-column layout... but if I can't get it to work, we can just move on and establish this work as an enhancement objective for the next conference cycle.
