### ISSUE TITLE
Bootstrap - cards default to height: 100%

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#82]
in `_sass/partials/_helper.scss`, we have 
```
.card { 
height: 100%;
}
```
Is this helping anyone? Seems suspect.

**Comment by dzoladz** [comment]
`.card` is getting used several times on the lodging section of the site.
<img width="620" alt="Screen Shot 2020-06-25 at 11 16 58 AM" src="https://user-images.githubusercontent.com/10561752/85747843-a2922f00-b6d5-11ea-807a-63d6530ad98e.png">

Since we're a virtual conference this year, the lodging sections have been disabled in `_config.yml`. However, our architecture needs to support face-to-face conferences and physical locations for future events.

Can you enable the lodging sections and see if the height declaration is necessary?

**Comment by kenirwin** [comment]
sure - sounds good. seems like a terrible default thing to do to a card. if it is necessary, I'll try to set a `. card .tall-card` class to handle that.
